parts/urls.py
from django.conf.urls import patterns, url

from parts.views import (CreateNewAssignments, CreateCongregation, ChangeCongregation, 
  ListAssignments, Overview, EditAssignments, AssignPart, ShowPublisher, 
  UpdatePublisher, DeletePublisher, ListPublishers, CreatePublisher, AssignAssistant, 
  UpdateCounsel, SetNextCounselPoint, SetSetting, PrintSchedule)
#  For this project view and url names will follow verb_noun naming pattern.

urlpatterns = patterns('',
  url(r'^update_schedule/$',CreateNewAssignments.as_view(), name='create_assignments'),
  url(r'^congregation/create/$',CreateCongregation.as_view(), name='create_congregation'),
  url(r'^congregation/change/$',ChangeCongregation.as_view(), name='change_congregation'),
  url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)/$', ListAssignments.as_view(), name="list_assignments"),
  url(r'^$',Overview.as_view(), name='overview'),
  url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)/edit/$', EditAssignments.as_view(), name="edit_assignments"),

  url(r'^(?P<pk>\d+)/assign/$',AssignPart.as_view(), name='assign_part'),
  url(r'^(?P<pk>\d+)/assign-assistant/$',AssignAssistant.as_view(), name='assign_assistant_to_part'),
  
  url(r'^publishers/$',ListPublishers.as_view(), name='list_publishers'),
  url(r'^publisher/(?P<pk>\d+)/show/$',ShowPublisher.as_view(), name='show_publisher'),
  url(r'^publisher/(?P<pk>\d+)/edit/$',UpdatePublisher.as_view(), name='edit_publisher'),
  url(r'^publisher/(?P<pk>\d+)/delete/$',DeletePublisher.as_view(), name='delete_publisher'),
  url(r'^publisher/create/$',CreatePublisher.as_view(), name='create_publisher'),

  url(r'^part/(?P<pk>\d+)/counsel/$',UpdateCounsel.as_view(), name='update_counsel'),
  url(r'^part/(?P<pk>\d+)/next-counsel-point/', SetNextCounselPoint.as_view(), name='set_next_counsel_point'),
  url(r'^part/(?P<pk>\d+)/setting/', SetSetting.as_view(), name='set_setting'),
  url(r'^print/$',PrintSchedule.as_view(), name='print_schedule'),
  
    



  # Example: /2012/nov/10/
  # url(r'^meeting/(?P<year>\d{4})/(?P<month>[-\w]+)/(?P<day>\d+)/$', ShowMeeting.as_view(), name='show_meeting'),
  # url(r'^meeting/(?P<year>\d{4})/(?P<month>[-\w]+)/(?P<day>\d+)/edit/$', ShowMeeting.as_view(), name='show_meeting'),
  # # url(r'^meeting/edit/$', EditMeeting.as_view(), name='edit_meeting'),
  # url(r'^(?P<pk>\d+)/$', EditTag.as_view(), name='edit_tag'),
 )

schedules/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# from django.conf import settings
# from django.conf.urls.static import static
from parts.views import Overview

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'YesTags.views.home', name='home'),
    # url(r'^YesTags/', include('YesTags.foo.urls')),
		url(r'^admin/', include(admin.site.urls)),
    url(r'^parts/', include('parts.urls')),
    url(r'^auth/', include('authentication.urls')),
    url(r'^$',Overview.as_view(), name='overview'),
)

# ## This is used to serve user uploaded files in dev mode
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parts/models.py
from django.db import models
# # from django.contrib.auth.models import settings.AUTH_USER_MODEL
# from django.conf import settings
from django.conf import settings


MONDAY=0
TUESDAY=1
WEDNESDAY=2
THURSDAY=3
FRIDAY=4
SATURDAY=5
SUNDAY=6
DAYS_OF_WEEK=(
  (MONDAY,'Monday'),
  (TUESDAY,'Tuesday'),
  (WEDNESDAY,'Wednesday'),
  (THURSDAY,'Thursday'),
  (FRIDAY,'Friday'),
  (SATURDAY,'Saturday'),
  (SUNDAY,'Sunday'),
)
class Meeting(models.Model):
  name = models.CharField(max_length=64)
  order = models.IntegerField()
  def __unicode__(self): return self.name

class Category(models.Model):
  name = models.CharField(max_length=64)
  meeting = models.ForeignKey(Meeting)
  def __unicode__(self): return self.name
  def assistant_suggestions(self, ex, start_date=None):
    return Publisher.objects.raw("""
      select `parts_publisher`.*
      FROM `parts_publisher`
      LEFT OUTER JOIN `parts_publisher_categories` ON (`parts_publisher`.`id` = `parts_publisher_categories`.`publisher_id`)
      
      left outer join (
        SELECT `parts_publisher`.`id` as publisher_id,  MAX(`parts_assignment`.`date`) AS `last` 
        FROM `parts_publisher` 
        LEFT OUTER JOIN `parts_assignment` ON (`parts_publisher`.`id` = `parts_assignment`.`assistant_id`) 
        group by `parts_publisher`.`id`
        ) as assignments on (`parts_publisher`.`id` = `assignments`.`publisher_id`) 
      left outer join (
        SELECT `parts_publisher`.`id` as publisher_id,  MAX(`parts_assignment`.`date`) AS `last` 
        FROM `parts_publisher` 
        LEFT OUTER JOIN `parts_assignment` ON (`parts_publisher`.`id` = `parts_assignment`.`publisher_id`) 
        ) as all_assignments on (`parts_publisher`.`id` = `assignments`.`publisher_id`) 
      where parts_publisher_categories.category_id=%s and `parts_publisher`.`id` != %s
      order by assignments.last, all_assignments.last;
      """ % (self.pk, ex)) 
  
  @property
  def suggestions(self, start_date=None):
    return Publisher.objects.raw("""
      select `parts_publisher`.*
      FROM `parts_publisher`
      LEFT OUTER JOIN `parts_publisher_categories` ON (`parts_publisher`.`id` = `parts_publisher_categories`.`publisher_id`)
      left outer join (
        SELECT `parts_publisher`.`id` as publisher_id,  MAX(`parts_assignment`.`date`) AS `last` 
        FROM `parts_publisher` 
        LEFT OUTER JOIN `parts_assignment` ON (`parts_publisher`.`id` = `parts_assignment`.`publisher_id`) 
        LEFT OUTER JOIN `parts_part` ON (`parts_part`.`id` = `parts_assignment`.`part_id`) 
        WHERE `parts_part`.`category_id` = %s
        GROUP BY `parts_publisher`.`id`
        ) as assignments on (`parts_publisher`.`id` = `assignments`.`publisher_id`) 
      left outer join (
        SELECT `parts_publisher`.`id` as publisher_id,  MAX(`parts_assignment`.`date`) AS `last` 
        FROM `parts_publisher` 
        LEFT OUTER JOIN `parts_assignment` ON (`parts_publisher`.`id` = `parts_assignment`.`publisher_id`) 
        GROUP BY `parts_publisher`.`id`
        ) as all_assignments on (`parts_publisher`.`id` = `all_assignments`.`publisher_id`) 
      where parts_publisher_categories.category_id=%s
      group by `parts_publisher`.`id`
      order by assignments.last, all_assignments.last;
      """ % (self.pk, self.pk)) 


    # You can't use order_by related model with distinct(), So I do this:
    # return Publisher.objects.filter(assignments__part__category_id=self.id).annotate(last_assignment=models.Max('assignments__date')).order_by('last_assignment')
    # last_assigned = Publisher.objects.filter(assignments__part__category_id=self.id).annotate(last_assignment=Max('assignments__date')).order_by('last_assignment')
    # never_assigned = Publisher.objects.filter(categories__id=9).exclude(assignments__part__category_id=self.id)
    # return list(never_assigned) + list(last_assigned)
    # return self.publishers.annotate(models.Max("assignments__date")).order_by('assignments__date__max')
    # return Publisher.objects.raw("select parts_publisher.*, max(parts_assignment.date) as last_date from parts_part inner join parts_assignment on part_id=parts_part.id inner join parts_publisher on publisher_id=parts_publisher.id where category_id=%s group by publisher_id order by last_date" % self.pk)
  # @property
  # def top_suggestion(self, start_date=None):
  #   return Publisher.objects.raw("select parts_publisher.*, max(parts_assignment.date) as last_date from parts_part inner join parts_assignment on part_id=parts_part.id inner join parts_publisher on publisher_id=parts_publisher.id where category_id=%s group by publisher_id order by last_date limit 1" % self.pk)[0]
class Setting(models.Model):
  name = models.CharField(max_length=130)
  def __unicode__(self): return self.name

class CounselPoint(models.Model):
  name = models.CharField(max_length=64)
  def __unicode__(self): return self.name

class Congregation(models.Model):
  name = models.CharField(max_length=64)
  weekday = models.IntegerField(choices=DAYS_OF_WEEK)
  admins = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='admin')
  schedule_public = models.BooleanField(default=False)
  school_overseer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='school_overseer_for', null=True, blank=True)
  coordinator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='coordinator_for', null=True, blank=True)
  sound_scheduler = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sound_servant_for', null=True, blank=True)
  stage_scheduler = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='stage_scheduler_for', null=True, blank=True)
  attendants_scheduler = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='attendants_scheduler_for', null=True, blank=True)
  auto_fill_school = models.BooleanField(default=True)
  auto_fill_service_meeting = models.BooleanField(default=True)
  # num_microphone_handlers = models.IntegerField(default=2)
  # num_attendants = models.IntegerField(default=2)
  def __unicode__(self): return self.name

GENDER_MALE=1
GENDER_FEMALE=2
GENDERS=(
  (GENDER_MALE,'Male'),
  (GENDER_FEMALE,'Female')
  )
class Publisher(models.Model):
  def __unicode__(self): return self.full_name
  last_name = models.CharField(max_length=64, default="")
  first_name = models.CharField(max_length=64, default="")
  gender = models.IntegerField(choices=GENDERS, default=GENDER_MALE)
  congregation = models.ForeignKey(Congregation, related_name='publishers')
  counsel_point = models.ForeignKey(CounselPoint, related_name='publishers', blank=True, null=True)
  categories = models.ManyToManyField(Category, related_name='publishers')
  @property
  def full_name(self): return "%s %s" % (self.first_name, self.last_name)
  @property
  def order_name(self): return "%s, %s" % (self.last_name, self.first_name)

class Part(models.Model):
  def __unicode__(self): 
    if self.theme: return self.theme
    else: return self.material
  theme = models.CharField(max_length=64, default="", blank=True)
  material = models.CharField(max_length=64, default="", blank=True)
  order = models.IntegerField()
  date = models.DateField()
  category = models.ForeignKey(Category, related_name='parts')

class Assignment(models.Model):
  @property
  def title(self): return self.__unicode__
  def __unicode__(self): return self.part.theme or self.part.material
  date = models.DateField()
  part = models.ForeignKey(Part, related_name='assignments')
  # category = models.ForeignKey(Category, related_name='assignments')
  counsel_point = models.ForeignKey(CounselPoint, related_name='assignments', null=True, blank=True)
  publisher = models.ForeignKey(Publisher, related_name='assignments', null=True, blank=True)
  setting = models.ForeignKey(Setting, related_name='assignments', null=True, blank=True)
  assistant = models.ForeignKey(Publisher, related_name='assistant_assignments', null=True, blank=True)
  counsel = models.CharField(max_length=128, default="", blank=True)
  timing = models.CharField(max_length=8, default="", blank=True)
  congregation = models.ForeignKey(Congregation, related_name='assignments')
  next_counsel_point = models.ForeignKey(CounselPoint, null=True, blank=True, related_name="next")
  exercises_done = models.NullBooleanField(blank=True)
  @property
  def category(self): return self.part.category
  @property
  def suggestions(self): 
    # l=None
    # # For Service Meeting Parts, try to use elders first
    # if self.category.pk == 9: l = Publisher.objects.filter(categories__id=11).order_by('assignments__date').distinct()[:10]
    return self.part.category.suggestions

parts/forms.py
from django import forms
from parts.models import Assignment, Publisher, CounselPoint, Category, GENDERS

class FormWithUserMixin(object):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(FormWithUserMixin, self).__init__(*args, **kwargs)

class AssignmentForm(forms.ModelForm):
  class Meta:
    model = Assignment
    fields = ('publisher',)

class CounselForm(forms.ModelForm):
  class Meta:
    model = Assignment
    fields = ('counsel_point', 'counsel', 'timing')
  counsel_point = forms.ModelChoiceField(queryset=CounselPoint.objects.all(), initial="", widget=forms.Select(attrs={'placeholder':'Counsel Point','class':'form-control'}), required=False)
  next_counsel_point = forms.ModelChoiceField(queryset=CounselPoint.objects.all(), initial="", widget=forms.Select(attrs={'placeholder':'Counsel Point','class':'form-control'}), required=False)
  setting = forms.CharField(initial="", widget=forms.TextInput(attrs={'placeholder':'Setting','class':'form-control'}), required=False)
  counsel = forms.CharField(initial="", widget=forms.Textarea(attrs={'placeholder':'Notes','class':'form-control'}), required=False)
  timing = forms.CharField(initial="", widget=forms.TextInput(attrs={'placeholder':'Timing','class':'form-control'}), required=False)
  exercises_done = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-control'}), required=False)

class AssistantForm(forms.ModelForm):
  class Meta:
    model = Assignment
    fields = ('assistant',)
  assistant = forms.ModelChoiceField(queryset=Publisher.objects.all(), initial="", widget=forms.Select(attrs={'placeholder':'Counsel Point','class':'form-control'}), required=False)
  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user')
    super(AssistantForm, self).__init__(*args, **kwargs)
    self.fields['assistant'].queryset = Publisher.objects.filter(congregation=self.user.congregation, categories=17)

class PublisherForm(forms.ModelForm):
  class Meta:
    model = Publisher
    fields = ('last_name', 'first_name', 'gender','counsel_point', 'categories')
  last_name = forms.CharField(initial="", widget=forms.TextInput(attrs={'placeholder':'Last','class':'form-control'}), required=False)
  first_name = forms.CharField(initial="", widget=forms.TextInput(attrs={'placeholder':'First','class':'form-control'}), required=False)
  gender = forms.ChoiceField(choices=GENDERS, initial="", widget=forms.Select(attrs={'placeholder':'Counsel Point','class':'form-control'}), required=False)
  counsel_point = forms.ModelChoiceField(queryset=CounselPoint.objects.all(), initial="", widget=forms.Select(attrs={'placeholder':'Counsel Point','class':'form-control'}), required=False)
  categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), initial="", widget=forms.SelectMultiple(attrs={'placeholder':'Counsel Point','class':'form-control multi-drop'}), required=False)

parts/templates/parts/assign_assistant.html
{{object.assistant.full_name}}

parts/templates/parts/assign_part.html
{{object.publisher.full_name}}

parts/templates/parts/assignment.html
<li class="list-group-item">
  {% if not enable_edit %}
    {% if assignment.part.category_id == 6 or assignment.part.category_id == 7 or assignment.part.category_id == 8 %}
      <a href="{% url "update_counsel" assignment.pk %}">
    {% endif %}
  {% endif %}
  <div class="theme">
    {% if assignment.part.theme %}
      {% if assignment.part.category_id == 7 or assignment.part.category_id == 8 %}
        {{assignment.part.category}}: {{assignment.part.theme}}
      {% else %}
        {{assignment.part.theme}}
      {% endif %}
    {% else %}
      {{assignment.part.category}}: {{assignment.part.material}}
    {% endif %}
  </div>
  {% if enable_edit %}
    <div class="btn-group select">
      <i class="dropdown-arrow"></i>
      <button data-toggle="dropdown" class="btn dropdown-toggle clearfix btn-sm">
        <span id="assignment-{{assignment.pk}}-label" class="filter-option pull-left">{{assignment.publisher|default:"Choose a publisher"}}</span>&nbsp;<span class="caret"></span>
      </button>
      <ul role="menu" class="dropdown-menu">
        {% for pub in assignment.suggestions %}
          <li rel="{{pub.pk}}" {% if pub = assignment.publisher %}class="selected"{% endif %}><a class="opt " href="#" onclick="assign_part('{% url "assign_part" assignment.pk %}', {{pub.pk}}, 'assignment-{{assignment.pk}}-label')" tabindex="-1"><span class="pull-left">{{pub.full_name}}</span></a></li>
        {% endfor %}
      </ul>
    </div>
    {% if assignment.part.category_id == 7 or assignment.part.category_id == 8 %}
      {% if assignment.publisher.gender = 2 %}
        <div class="btn-group select">
          <i class="dropdown-arrow"></i>
          <button data-toggle="dropdown" class="btn dropdown-toggle clearfix btn-sm">
            <span id="assignment-assistant-{{assignment.pk}}-label" class="filter-option pull-left">{{assignment.assistant|default:"Choose an assistant"}}</span>&nbsp;<span class="caret"></span>
          </button>
          <ul role="menu" class="dropdown-menu">
            {% for pub in assistants %}
              <li rel="{{pub.pk}}" {% if pub = assignment.assistant %}class="selected"{% endif %}>
                <a class="opt " href="#" onclick="assign_assistant_to_part('{% url "assign_assistant_to_part" assignment.pk %}', {{pub.pk}}, 'assignment-assistant-{{assignment.pk}}-label')" tabindex="-1">
                  <span class="pull-left">{{pub.full_name}}</span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endif %}
    {% if assignment.part.category_id == 12 %}
        <div class="btn-group select">
          <i class="dropdown-arrow"></i>
          <button data-toggle="dropdown" class="btn dropdown-toggle clearfix btn-sm">
            <span id="assignment-assistant-{{assignment.pk}}-label" class="filter-option pull-left">{{assignment.assistant|default:"Choose an assistant"}}</span>&nbsp;<span class="caret"></span>
          </button>
          <ul role="menu" class="dropdown-menu">
            {% for pub in assignment.suggestions %}
              <li rel="{{pub.pk}}" {% if pub = assignment.assistant %}class="selected"{% endif %}>
                <a class="opt " href="#" onclick="assign_assistant_to_part('{% url "assign_assistant_to_part" assignment.pk %}', {{pub.pk}}, 'assignment-assistant-{{assignment.pk}}-label')" tabindex="-1">
                  <span class="pull-left">{{pub.full_name}}</span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
    {% endif %}
  {% else %}
    <div class="assignee">{{assignment.publisher.full_name}}{% if assignment.assistant %} & {{assignment.assistant.full_name}}{% endif %}</div>
  {% endif %}
  {% if not enable_edit %}{% if assignment.part.category_id == 6 or assignment.part.category_id == 7 or assignment.part.category_id == 8 %}</a>{% endif %}{% endif %}
</li>

parts/templates/parts/counsel_form.html
{% extends "design/header.html" %}
{% block content %}
  <form id="counsel_form" method="POST">
    {% csrf_token %}
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{{object.part.category.name}}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{% if object.publisher %}<a href="{% url "show_publisher" object.publisher.pk %}">{{object.publisher.full_name}}</a>{% endif %}{% if object.assistant %} & <a href="{% url "show_publisher" object.assistant.pk %}">{{object.assistant.full_name}}</a>{% endif %}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{{object.part.theme}}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{{object.part.material}}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{% if object.publisher %}{% if object.publisher.counsel_point %}{{object.publisher.counsel_point.name}}{% else %}No Counsel Point Assigned{% endif %}{% else %}No Counsel Point Assigned{% endif %}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="btn-group select btn-block">
          <i class="dropdown-arrow"></i>
          <button data-toggle="dropdown" class="btn dropdown-toggle clearfix btn-block">
            <span id="setting-{{object.pk}}-label" class="filter-option pull-left">{{object.setting.name|default:"Choose a setting"}}</span>&nbsp;<span class="caret"></span>
          </button>
          <ul role="menu" class="dropdown-menu">
            {% for setting in my_setting_list %}
              <li rel="{{setting.pk}}" {% if setting = object.setting %}class="selected"{% endif %}>
                <a class="opt " href="#" onclick="set_setting('{% url "set_setting" object.pk %}', {{setting.pk}}, 'setting-{{object.pk}}-label')" tabindex="-1">
                  <span class="pull-left">{{setting.name}}</span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-3 col-md-offset-3">
        <div class="theme">{{form.timing}}{{setting_list}}</div>
      </div>
      <div class="col-md-3">
        <label class="checkbox theme" for="id_exercises_done">
          <input type="checkbox" name="exercises_done" id="id_exercises_done" class="form-control" data-toggle="checkbox">
          Exercises Done
        </label>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="btn-group select btn-block">
          <i class="dropdown-arrow"></i>
          <button data-toggle="dropdown" class="btn dropdown-toggle clearfix btn-block">
            <span id="next-counsel-{{object.pk}}-label" class="filter-option pull-left">{{object.next_counsel_point.name|default:"Next counsel point"}}</span>&nbsp;<span class="caret"></span>
          </button>
          <ul role="menu" class="dropdown-menu">
            {% for point in counsel_point_list %}
              <li rel="{{point.pk}}" {% if point = object.next_counsel_point %}class="selected"{% endif %}>
                <a class="opt " href="#" onclick="set_next_counsel_point('{% url "set_next_counsel_point" object.pk %}', {{point.pk}}, 'next-counsel-{{object.pk}}-label')" tabindex="-1">
                  <span class="pull-left">{{point.name}}</span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <div class="theme">{{form.counsel}}</div>
      </div>
    </div>
    <div class="row input-row">
      <div class="col-md-6 col-md-offset-3">
        <a class="btn btn-block btn-primary" href="{% url "list_assignments" year=object.date.year month=object.date.month day=object.date.day %}">Done</a>
      </div>
    </div>
  </form>
{% endblock content %}
{% block js %}
  <script type="text/javascript" src="{{STATIC_URL}}js/jquery.autosave.js"></script>
  <script type="text/javascript">
    function set_next_counsel_point(url, point_id, label){
      window.label_to_update = label;
      $.ajax({
        type: "POST",
        url: url,
        data: "next_counsel_point="+point_id+"&csrfmiddlewaretoken="+$('input[name="csrfmiddlewaretoken"]').val(),
        success: updateLabel,
      });
    }
    function set_setting(url, setting_id, label){
      window.label_to_update = label;
      $.ajax({
        type: "POST",
        url: url,
        data: "setting="+setting_id+"&csrfmiddlewaretoken="+$('input[name="csrfmiddlewaretoken"]').val(),
        success: updateLabel,
      });
    }
    function updateLabel(data){
      $('#'+window.label_to_update).html(data);
    }
    jQuery(function($) {
      // $("counsel_form").autosave();
      // $("#counsel_form").autosave({
      //   callbacks: {
      //     trigger: ["change", function() {
      //       var self = this;

      //       $("[name=save]").click(function() {
      //         self.save();
      //       });
      //     }],
      //     save: {
      //       options: {
      //         success: function() {
      //           alert("saved!");
      //         }
      //       }
      //     }
      //   }
      // });


    $('#counsel_form').autosave({
      callbacks: {
        scope:"all",
        save: {
          method: "ajax",
          options: {
            type: "POST"
          }
        }
       }
    });
    });
  </script>
{% endblock js %}

parts/templates/parts/new_assignments.html
{% extends "design/header.html" %}
{% block content %}
  <div class="row" id="name-section">
    <div class="col-md-6 col-md-offset-3 page-header">
      <h1>{{assignments.count}} New Assignments Created</h1>
    </div>
  </div>
{% endblock content %}

parts/templates/parts/publisher_confirm_delete.html
{% extends "design/header.html" %}
{% block content %}
  <h3>Delete {{object.full_name}}</h1>
  <form method="POST">{% csrf_token %}
    <div class="lead">Are you sure you want to delete {{object.full_name}}?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
  </form>
{% endblock content %}

parts/templates/parts/publisher_detail.html
{% extends "design/header.html" %}
{% block content %}
  <h3>{{object.full_name}}</h3>
  <div class="theme">Counsel Point: {{object.counsel_point.name}}</div>
  <div class="theme">Gender: {{object.get_gender_display}}</div>
  <h5>Privileges:</h5>
  <ul class="list-group">
    {% for object in object.categories.all %}
      <li class="list-group-item">{{object.name}}</li>
    {% endfor %}
  </ul>
  <a class="btn btn-primary" href="{% url "create_publisher" %}">Create</a>
  <a class="btn" href="{% url "edit_publisher" object.pk %}">Edit</a>
  <a class="btn btn-danger" href="{% url "delete_publisher" object.pk %}">Delete</a>
{% endblock content %}

parts/templates/parts/publisher_form.html
{% extends "design/header.html" %}
{% block content %}
  <h3>Edit {{object.full_name}}</h1>
  <form method="POST">{% csrf_token %}
    <div class="row input-row">{{form.first_name}}</div>
    <div class="row input-row">{{form.last_name}}</div>
    <div class="row input-row">{{form.gender}}</div>
    <div class="row input-row">{{form.counsel_point}}</div>
    <div class="row input-row">{{form.categories}}</div>
    <input type="submit" value="Save" class="btn">

    {% if object.pk %}
      <a class="btn" href="{% url "show_publisher" object.pk %}">Cancel</a>
      <a class="btn btn-danger" href="{% url "delete_publisher" object.pk %}">Delete</a>
    {% else %}
      <a class="btn" href="{% url "list_publishers"%}">Cancel</a>
    {% endif %}

  </form>
{% endblock content %}

parts/templates/parts/publisher_list.html
{% extends "design/header.html" %}
{% block content %}
  <ul class="list-group">
    {% for object in object_list %}
      <li class="list-group-item"><a href="{% url "show_publisher" object.pk %}">{{object.order_name}}</a></li>
    {% endfor %}
  </ul>
  <a class="btn btn-primary" href="{% url "create_publisher" %}">Create</a>
{% endblock content %}